#!/usr/bin/env python3

import random
import argparse, socket, time, json, select, struct, sys, math, os

BROADCAST = "FFFF"

ENABLE_LOG = True
ENABLE_PROFILING = False

if ENABLE_LOG:
    if os.path.exists("log.txt"):
        try:
            os.remove("log.txt")
        except FileNotFoundError:
            pass

def log(message):
    if not ENABLE_LOG:
        return
    with open("log.txt", "a+") as f:
        timestamp = time.strftime("%H:%M:%S") + f".{int(time.time() * 1000) % 1000:03d}"
        f.write(f"[{timestamp}] {message}\n")
        pass

class Command:
    def apply(self, state_machine: dict):
        pass

    def serialize(self) -> list[str]:
        return ""
    
class GetCommand(Command):
    def __init__(self, key: str):
        self.key = key
    
    def apply(self, state_machine: dict):
        return state_machine.get(self.key, None)
    
    def serialize(self) -> list[str]:
        return ["GET", self.key]
    
class PutCommand(Command):
    def __init__(self, key: str, value: str):
        self.key = key
        self.value = value
    
    def apply(self, state_machine: dict):
        state_machine[self.key] = self.value
        return None
    
    def serialize(self) -> list[str]:
        return ["PUT", self.key, self.value]
    
class LogEntry:
    def __init__(self, index: int, term: int, command: Command):
        self.index = index
        self.term = term
        self.command = command
    
class Replica:
    current_term = 0
    log: list[LogEntry] = []
    leader = None
    state_machine = {}
    last_heartbeat = 0
    voted_for = None
    election_start = None
    received_votes = 0
    commit_index = 0
    last_applied = 0
    next_index = {}
    match_index = {}
    unsent_log_entries = [] 
    
    # Profiles the message for performance analysis
    def profile(self, message: dict, direction: str):
        if not ENABLE_PROFILING:
            return
        profile_filename = f"profile+{self.id}+{direction}.json"
        if not os.path.exists(profile_filename):
            with open(profile_filename, "w") as f:
                json.dump({}, f)
        with open(profile_filename, "r+") as f:
            profile_data = json.load(f)
        message_type = message["type"]
        if message_type == "append_entries":
            message_type = "append_entries" if len(message["entries"]) > 0 else "heartbeat"
        if message_type not in profile_data:
            profile_data[message_type] = 0
        profile_data[message_type] += 1
        if "total" not in profile_data:
            profile_data["total"] = 0
        profile_data["total"] += 1
        with open(profile_filename, "w") as f:
            json.dump(profile_data, f)
    
    
    # Initializes the replica with the given port, id, and other replicas
    def __init__(self, port: str, id: str, others: list[str]):
        if ENABLE_PROFILING:
            if os.path.exists("profile+{self.id}+send.json.txt"):
                os.remove("profile+{self.id}+send.json.txt")
            if os.path.exists("profile+{self.id}+receive.json.txt"):
                os.remove("profile+{self.id}+receive.json.txt")
        self.LEADER_TIMEOUT_LENGTH = .5 + random.uniform(-0.5, 0.5)
        self.ELECTION_TIMEOUT_LENGTH = .5 + random.uniform(-0.1, 0.1)
        self.HEARTBEAT_FREQUENCY = 0.1

        self.port = port
        self.id = id
        self.others = others

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('localhost', 0))

        print(f"Replica {self.id} starting up")
        hello = { "src": self.id, "dst": BROADCAST, "leader": BROADCAST, "type": "hello" }
        self.send(hello)
        print(f"Sent hello message: {hello}")
        
    
    # Main loop to run the replica
    def run(self):
        while True:
            readable_sockets: tuple[socket.socket] = select.select([self.socket], [], [], .2)[0]
            if self.socket in readable_sockets:
                data: bytes = self.socket.recvfrom(65535)[0]
                msg = json.loads(data.decode('utf-8'))

                if msg["type"] in ["get", "put", "vote_request", "vote_response", "append_entries", "append_entries_response"]:
                    self.handle_message(msg)
            if self.leader == self.id and time.time() - self.last_heartbeat > self.HEARTBEAT_FREQUENCY:
                self.send_heartbeat()
            if self.voted_for is None and time.time() - self.last_heartbeat > self.LEADER_TIMEOUT_LENGTH:
                self.current_term += 1
                self.start_election()
            if self.voted_for == self.id and time.time() - self.election_start > self.ELECTION_TIMEOUT_LENGTH:
                self.start_election()

    # Sends a message to other replicas
    def send(self, message):
        self.profile(message, "send")
        self.socket.sendto(json.dumps(message).encode('utf-8'), ('localhost', self.port))

    # Handles incoming messages
    def handle_message(self, msg):
        self.profile(msg, "receive")
        if msg["type"] == "vote_request":
            self.handle_request_vote(msg)
        elif msg["type"] == "vote_response":
            self.handle_vote_response(msg)
        elif msg["type"] == "append_entries":
            self.handle_append_entries(msg)
        elif msg["type"] == "append_entries_response":
            self.handle_append_entries_ack(msg)
        elif self.leader == self.id:
            if msg["type"] == "put":
                self.handle_put(msg)
            elif msg["type"] == "get":
                self.handle_get(msg)
            else:
                raise RuntimeError(f"Unknown message type: {msg['type']}")
        else:
            response = self.build_response(msg, "redirect")
            self.send(response)
            return
        
    # Handles GET requests
    def handle_get(self, msg):
        for entry in reversed(self.log):
            if entry.index <= self.commit_index:
                break
            if isinstance(entry.command, PutCommand) and entry.command.key == msg["key"]:
                if entry.index > self.commit_index:
                    response = self.build_response(msg, "redirect")
                    self.send(response)
                    return
        try:
            key = msg["key"]
            value = GetCommand(key).apply(self.state_machine)
            response = self.build_response(msg, "ok", value=value)
            self.send(response)
            if value is None:
                log(f"GET for key [{key}] returned null")
                for entry in self.log:
                    if isinstance(entry.command, PutCommand) and entry.command.key == key:
                        log(f"Null value is in log at index {entry.index}")
                        log(f"Current commit index is {self.commit_index}")
                for i in range(1, self.commit_index + 1):
                    if not any(entry.index == i for entry in self.log):
                        log(f"Missing log entry at index {i}")
            else: 
                log(f"Replica {self.id} GET {key} -> {value} [MID: {msg['MID']}]")
        except Exception as e:
            response = self.build_response(msg, "fail")
            self.send(response)
        
    # Handles PUT requests
    def handle_put(self, msg):
        try:
            # add command to log
            key = msg["key"]
            value = msg["value"]
            log_item = LogEntry(self.get_next_log_index(), self.current_term, PutCommand(key, value))
            self.log.append(log_item)
            # send ack
            response = self.build_response(msg, "ok")
            self.send(response)
            # send append entries
            self.unsent_log_entries.append(log_item)
            if len(self.unsent_log_entries) >= 1:
                self.send_append_entries(self.unsent_log_entries)
                self.unsent_log_entries = []
            log(f"Replica {self.id} PUT {key} -> {value} [MID: {msg['MID']}, index: {log_item.index}]")
        except Exception as e:
            response = self.build_response(msg, "fail")
            self.send(response)
            
    # Gets the next log index
    def get_next_log_index(self) -> int:
        return self.get_last_log_index() + 1
    
    # Builds a response message
    def build_response(self, msg: dict, type: str, **kwargs):
        response = {
            "src": self.id,
            "dst": msg["src"],
            "leader": self.leader if self.leader is not None else BROADCAST,
            "type": type,
        }
        if "MID" in msg:
            response["MID"] = msg["MID"]
        response.update(kwargs)
        return response
        
    # Requests votes from other replicas
    def request_vote(self):
        vote_request = {
            "src": self.id,
            "dst": BROADCAST,
            "leader": BROADCAST,
            "candidate_id": self.id,
            "type": "vote_request",
            "term": self.current_term,
            "last_log_index": self.get_last_log_index(),
            "last_log_term": self.get_last_log_term()
        }
        self.send(vote_request)
        log(f"Replica {self.id} sent vote request.")
        
    # Gets the term of the last log entry
    def get_last_log_term(self):
        last_log_index = self.get_last_log_index()
        return self.get_entry(last_log_index).term if last_log_index > 0 else 0
    
    # Gets the index of the last log entry
    def get_last_log_index(self):
        return max([entry.index for entry in self.log]) if self.log else 0
    
    # Handles vote requests
    def handle_request_vote(self, msg: dict):
        # If request is from an old term, vote against
        if msg["term"] < self.current_term:
            self.respond_not_grant_vote(msg)
            log(f"Replica {self.id} voted against {msg['candidate_id']} because their term is too old")
            return
        # If already voted for someone else, vote against
        if self.voted_for is not None and self.voted_for != msg["candidate_id"]:
            # But if the old vote is stale, reset electon
            if time.time() - self.election_start < self.ELECTION_TIMEOUT_LENGTH:
                self.respond_not_grant_vote(msg)
                log(f"Replica {self.id} voted against {msg['candidate_id']} because it already voted for {self.voted_for}")
                return
            else:
                self.reset_election_values()
        # If candidate's log is not up to date, vote against
        if (msg["last_log_term"] < self.get_last_log_term()) or \
           (msg["last_log_term"] == self.get_last_log_term() and msg["last_log_index"] < self.get_last_log_index()):
            self.respond_not_grant_vote(msg)
            log(f"Replica {self.id} voted against {msg['candidate_id']} because their log is not up to date")
            return
        # Otherwise, vote for the candidate
        self.voted_for = msg["candidate_id"]
        self.last_heartbeat = time.time()
        self.election_start = time.time()
        self.respond_grant_vote(msg)
        log(f"Replica {self.id} voted for {msg['candidate_id']}")
            
    # Responds with a granted vote
    def respond_grant_vote(self, msg: dict):
        vote_response = self.build_response(msg, "vote_response", term=self.current_term, vote_granted=True)
        self.send(vote_response)
            
    # Responds with a not granted vote
    def respond_not_grant_vote(self, msg: dict):
        vote_response = self.build_response(msg, "vote_response", term=self.current_term, vote_granted=False)
        self.send(vote_response)
        
    # Handles vote responses
    def handle_vote_response(self, msg: dict):
        log(f"Replica {self.id} received {'yay' if msg['vote_granted'] else 'nay'} vote from {msg['src']}")
        if msg["vote_granted"]:
            self.received_votes += 1
            log(f"Replica {self.id} received vote. Current votes: {self.received_votes}")
            if self.received_votes > (len(self.others) / 2.0):
                self.become_leader()
        else:
            if msg["term"] > self.current_term:
                self.current_term = msg["term"]
                self.reset_election_values()
    
    # Resets election-related values
    def reset_election_values(self):
        self.voted_for = None
        self.election_start = None
        self.received_votes = 0

                
    # Becomes the leader
    def become_leader(self):
        self.reset_election_values()
        self.leader = self.id
        self.next_index = {replica: self.get_next_log_index() for replica in self.others}
        self.match_index = {replica: 0 for replica in self.others}
        self.send_heartbeat()
        log(f"Replica {self.id} is now the leader")
            
    # Sends a heartbeat to other replicas
    def send_heartbeat(self):
        if len(self.unsent_log_entries) != 0:
            self.send_append_entries(self.unsent_log_entries)
            self.unsent_log_entries = []
        else:
            self.send_append_entries([])
        
    # Gets a log entry by index
    def get_entry(self, index: int) -> LogEntry:
        for entry in self.log:
            if entry.index == index:
                return entry
        return None
        
    # Sends append entries to other replicas
    def send_append_entries(self, entries: list[LogEntry]):
        if len(entries) > 0:
            before_index = min([entry.index for entry in entries]) - 1
        else:
            before_index = self.get_last_log_index()
        request = {
            "src": self.id,
            "dst": BROADCAST,
            "leader": self.id,
            "type": "append_entries",
            "term": self.current_term,
            "prev_log_index": before_index,
            "prev_log_term": self.get_entry(before_index).term if before_index > 0 else 0,
            "leader_commit": self.commit_index,
            "entries": self.log_to_entries(entries)
        }
        self.last_heartbeat = time.time()
        self.send(request)
    
    # Handles append entries requests
    def handle_append_entries(self, msg: dict):
        if msg["term"] >= self.current_term:
            self.reset_election_values()
            self.current_term = msg["term"]
            self.leader = msg["leader"]
            self.last_heartbeat = time.time()
            if self.is_log_consistent(msg):
                self.update_log_and_state_machine(msg)
                if len(msg["entries"]) != 0:
                    response = self.build_response(msg, "append_entries_response", current_index=self.get_last_log_index(), term=self.current_term, success=True)
                    self.send(response)
            else:
                self.send_append_entries_failure(msg)
        else:
            log(f"(Replica {self.id}) Append entries from {msg['src']} failed: term is too old, {msg['term']} < {self.current_term}")
            self.send_append_entries_failure(msg)
            
    # Handles append entries acknowledgments
    def handle_append_entries_ack(self, msg: dict):
        log(f"Replica {self.id} received append entries ack from {msg['src']}")
        if msg["success"]:
            self.match_index[msg["src"]] = msg["current_index"]
            self.next_index[msg["src"]] = msg["current_index"] + 1
            all_indices = list(self.match_index.values()) + [self.get_last_log_index()]
            highest_common_index = sorted(all_indices)[math.ceil(len(all_indices) / 2.0) - 1]
            if highest_common_index > self.commit_index:
                self.commit_index = highest_common_index
                self.make_commits()
        else:
            if msg["term"] > self.current_term:
                self.current_term = msg["term"]
                self.leader = None
            else:
                self.next_index[msg["src"]] = max(1, self.next_index[msg["src"]] - 1)
                log(f"Replica {self.id} decremented next index for {msg['src']} to {self.next_index[msg['src']]}")
                self.send_append_entries([entry for entry in self.log if entry.index >= self.next_index[msg["src"]]])

    # Checks if the log is consistent with the given message
    def is_log_consistent(self, msg: dict) -> bool:
        entry_at_prev_index = self.get_entry(msg["prev_log_index"])
        if len(msg["entries"]) == 0:
            return True
        if msg["prev_log_index"] == 0:
            return True
        if not entry_at_prev_index:
            log(f"(Replica {self.id}) Append entries from {msg['src']} failed: no entry at index {msg['prev_log_index']}")
            return False
        if entry_at_prev_index.term != msg["prev_log_term"]:
            log(f"(Replica {self.id}) Append entries from {msg['src']} failed: term mismatch at index {msg['prev_log_index']} "
                f"(expected {entry_at_prev_index.term}, got {msg['prev_log_term']})")
            return False
        return True

    # Updates the log and state machine with entries from the given message
    def update_log_and_state_machine(self, msg: dict):
        new_entries = self.entries_to_log(msg["entries"])
        if len(new_entries) != 0:
            entries_to_delete_from = self.get_last_log_index()
            for entry in new_entries:
                existing_entry = self.get_entry(entry.index)
                if existing_entry and existing_entry.term != entry.term:
                    entries_to_delete_from = min(entries_to_delete_from, entry.index)
                    break
            self.log = list(filter(lambda entry: entry.index <= entries_to_delete_from, self.log))
            existing_indices = [entry.index for entry in self.log]
            adding_entries = [entry for entry in new_entries if entry.index not in existing_indices]
            self.log += adding_entries
        if msg["leader_commit"] > self.commit_index:
            if len(new_entries) > 0:
                self.commit_index = min(msg["leader_commit"], max([entry.index for entry in new_entries]))
            else:
                self.commit_index = msg["leader_commit"]
            self.make_commits()
            log(f"Replica {self.id} committed up to index {self.commit_index}")
    
    # Commits pending log entries to the state machine up to the commit index
    def make_commits(self):
        for entry in self.log:
            if entry.index > self.last_applied and entry.index <= self.commit_index:
                entry.command.apply(self.state_machine)
                log(f"Replica {self.id} applied log entry {entry.index} {entry.command.serialize()}")
        self.last_applied = self.commit_index

    # Sends a failure response for append entries
    def send_append_entries_failure(self, msg: dict):
        response = self.build_response(msg, "append_entries_response", term=self.current_term, success=False)
        self.send(response)
            
    # Converts log entries to a list of serialized entries
    def log_to_entries(self, log: list[LogEntry]) -> list[list[str]]:
        entries = []
        for entry in log:
            entries.append([entry.index, entry.term, entry.command.serialize()])
        return entries
    
    # Converts a list of serialized entries to log entries
    def entries_to_log(self, entries: list[list[str]]) -> list[LogEntry]:
        log = []
        for index, term, serialized in entries:
            if serialized[0] == "GET":
                log.append(LogEntry(index, term, GetCommand(serialized[1])))
            elif serialized[0] == "PUT":
                log.append(LogEntry(index, term, PutCommand(serialized[1], serialized[2])))
        return log

    # Starts an election
    def start_election(self):
        self.received_votes = 1
        self.leader = None
        self.voted_for = self.id
        self.election_start = time.time()
        self.request_vote()
            
    

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help="Port number to communicate")
    parser.add_argument('id', type=str, help="ID of this replica")
    parser.add_argument('others', metavar='others', type=str, nargs='+', help="IDs of other replicas")
    args = parser.parse_args()
    replica = Replica(args.port, args.id, args.others)
    replica.run()
